"""应用和路由模块的共享导入。"""

from __future__ import annotations

import asyncio
import json
from datetime import datetime
from pathlib import Path
from typing import Any

from fastapi import APIRouter, Depends, FastAPI, HTTPException
from fastapi import Request as FastAPIRequest
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse, HTMLResponse, JSONResponse
from fastapi.staticfiles import StaticFiles

from server.core import (
    BASE_URL,
    CLEANUP_INTERVAL_SECONDS,
    DEFAULT_PORT,
    DEVICE_SCALE_FACTOR,
    MAP_COMPLETE_DELAY_MS,
    MAP_READY_FALLBACK_TIMEOUT_MS,
    MAP_READY_TIMEOUT_MS,
    MULTI_FITVIEW_PADDING,
    PUBLIC_DIR,
    SCREENSHOT_CONCURRENCY,
    SCREENSHOT_DELAY_MS,
    SHARE_MAP_ZOOM,
    SHARE_MAP_ZOOMS,
    SHARE_POLYGON_STYLE,
    SINGLE_FITVIEW_PADDING,
    SINGLE_REGION_DEFAULT_ZOOM,
    SINGLE_REGION_ZOOM,
    SNAPSHOT_DIR,
    TASK_MAX_AGE_SECONDS,
    VIEWPORT,
    RuntimeState,
    SnapshotContext,
    amap_key,
    amap_security_code,
    build_lifespan,
    playwright_executable_path,
    shutdown_runtime_resources,
)
from server.model import (
    CityRequest,
    CityShareQuery,
    CitySnapshotCreateRequest,
    DistrictRequest,
    NationRegionRequest,
    NationShareQuery,
    NationSnapshotCreateRequest,
    ProvinceRegionRequest,
    ProvinceRequest,
    ProvinceShareQuery,
    ProvinceSnapshotCreateRequest,
    TrimmedStringModel,
)
from server.services import (
    RegionService,
    build_callback_payload,
    build_region_index,
    capture_share_page,
    choose_display_name,
    cleanup_expired_tasks,
    execute_snapshot_task,
    generate_task_id,
    get_origin,
    infer_level,
    load_task,
    looks_mojibake,
    normalize_text,
    persist_task,
    render_share_template,
    run_background_task,
    safe_task_path,
    schedule_background_task,
    schedule_snapshot_task,
    send_callback,
    send_callback_safely,
    serialize_public_task,
)

__all__ = [
    "APIRouter",
    "Any",
    "BASE_URL",
    "CORSMiddleware",
    "CLEANUP_INTERVAL_SECONDS",
    "CityRequest",
    "CityShareQuery",
    "CitySnapshotCreateRequest",
    "DEFAULT_PORT",
    "DEVICE_SCALE_FACTOR",
    "Depends",
    "DistrictRequest",
    "FastAPI",
    "FastAPIRequest",
    "FileResponse",
    "HTMLResponse",
    "HTTPException",
    "JSONResponse",
    "MAP_COMPLETE_DELAY_MS",
    "MAP_READY_FALLBACK_TIMEOUT_MS",
    "MAP_READY_TIMEOUT_MS",
    "MULTI_FITVIEW_PADDING",
    "NationRegionRequest",
    "NationShareQuery",
    "NationSnapshotCreateRequest",
    "Path",
    "PUBLIC_DIR",
    "ProvinceRegionRequest",
    "ProvinceRequest",
    "ProvinceShareQuery",
    "ProvinceSnapshotCreateRequest",
    "SCREENSHOT_CONCURRENCY",
    "SCREENSHOT_DELAY_MS",
    "SHARE_MAP_ZOOM",
    "SHARE_MAP_ZOOMS",
    "SHARE_POLYGON_STYLE",
    "SINGLE_FITVIEW_PADDING",
    "SINGLE_REGION_DEFAULT_ZOOM",
    "SINGLE_REGION_ZOOM",
    "SNAPSHOT_DIR",
    "SnapshotContext",
    "StaticFiles",
    "TASK_MAX_AGE_SECONDS",
    "TrimmedStringModel",
    "VIEWPORT",
    "RuntimeState",
    "asyncio",
    "amap_security_code",
    "build_lifespan",
    "datetime",
    "json",
    "amap_key",
    "playwright_executable_path",
    "send_callback",
    "run_background_task",
    "send_callback_safely",
    "RegionService",
    "build_region_index",
    "choose_display_name",
    "infer_level",
    "looks_mojibake",
    "normalize_text",
    "capture_share_page",
    "build_callback_payload",
    "cleanup_expired_tasks",
    "execute_snapshot_task",
    "generate_task_id",
    "get_origin",
    "load_task",
    "persist_task",
    "safe_task_path",
    "schedule_background_task",
    "schedule_snapshot_task",
    "serialize_public_task",
    "render_share_template",
    "shutdown_runtime_resources",
]

# 路由模块在包初始化后使用上述共享名称
from server.api import (
    register_city_snapshot_routes,
    register_exception_handlers,
    register_national_snapshot_routes,
    register_province_snapshot_routes,
    register_system_routes,
)

__all__ += [
    "register_city_snapshot_routes",
    "register_exception_handlers",
    "register_national_snapshot_routes",
    "register_province_snapshot_routes",
    "register_system_routes",
]
