"""核心配置和运行时基础设施。"""

from server.core.config import (
    BASE_URL,
    CLEANUP_INTERVAL_SECONDS,
    DEFAULT_PORT,
    DEVICE_SCALE_FACTOR,
    MAP_COMPLETE_DELAY_MS,
    MAP_READY_FALLBACK_TIMEOUT_MS,
    MAP_READY_TIMEOUT_MS,
    MULTI_FITVIEW_PADDING,
    PUBLIC_DIR,
    ROOT_DIR,
    SCREENSHOT_CONCURRENCY,
    SCREENSHOT_DELAY_MS,
    SHARE_MAP_ZOOM,
    SHARE_MAP_ZOOMS,
    SHARE_POLYGON_STYLE,
    SINGLE_FITVIEW_PADDING,
    SINGLE_REGION_DEFAULT_ZOOM,
    SINGLE_REGION_ZOOM,
    SNAPSHOT_DIR,
    TASK_MAX_AGE_SECONDS,
    VIEWPORT,
    amap_key,
    amap_security_code,
    local_env,
    playwright_executable_path,
    read_dotenv,
)
from server.core.context import SnapshotContext
from server.core.lifecycle import build_lifespan, shutdown_runtime_resources
from server.core.runtime import RuntimeState

__all__ = [
    "BASE_URL",
    "CLEANUP_INTERVAL_SECONDS",
    "DEFAULT_PORT",
    "DEVICE_SCALE_FACTOR",
    "MAP_COMPLETE_DELAY_MS",
    "MAP_READY_FALLBACK_TIMEOUT_MS",
    "MAP_READY_TIMEOUT_MS",
    "MULTI_FITVIEW_PADDING",
    "PUBLIC_DIR",
    "ROOT_DIR",
    "RuntimeState",
    "SCREENSHOT_CONCURRENCY",
    "SCREENSHOT_DELAY_MS",
    "SHARE_MAP_ZOOM",
    "SHARE_MAP_ZOOMS",
    "SHARE_POLYGON_STYLE",
    "SINGLE_FITVIEW_PADDING",
    "SINGLE_REGION_DEFAULT_ZOOM",
    "SINGLE_REGION_ZOOM",
    "SNAPSHOT_DIR",
    "SnapshotContext",
    "TASK_MAX_AGE_SECONDS",
    "VIEWPORT",
    "amap_key",
    "amap_security_code",
    "build_lifespan",
    "local_env",
    "playwright_executable_path",
    "read_dotenv",
    "shutdown_runtime_resources",
]
